name: flutter_rte_tester
description: "A simple project to test rich text editors available in flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_quill: ^10.8.5
  html_editor_enhanced: ^2.6.0
  appflowy_editor: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
